### ISSUE TITLE
Pasting into the middle of text doesn't work

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [InfiniteAmmoInc/Yarn#1]
Copy/Paste to/from clipboard is working, but paste always adds to the end of the text instead of pasting at the cursor location.

**Comment by InfiniteAmmoInc** [comment]
Relevant code for this is found in app.js, line 448. (lines 424-434 are also relevant)

**Comment by seiyria** [comment]
This works for me currently. Is this reproducible only on mac?

**Comment by InfiniteAmmoInc** [comment]
Hmm yeah it might be a mac-only bug! Noel coded that part in Windows, so maybe that's why he wasn't aware of the problem.
