### ISSUE TITLE
Wrong carriage position

### ISSUE THREAD

**Issue by roxygen** [InfiniteAmmoInc/Yarn#102]
Hi! I tried to build/run application and got this problem with carriage. It placed with big offset from real one.

![image](https://user-images.githubusercontent.com/3707285/64935141-94c39980-d879-11e9-9fdf-2f57d2f94255.png)
![image](https://user-images.githubusercontent.com/3707285/64935166-c9375580-d879-11e9-914a-03b57779a34d.png)

**Comment by blurymind** [comment]
Hi Roxy, this is a problem with ace editor which yarn uses, I thought I had
fixed. Are you running it on Windows or Mac?

**Comment by blurymind** [comment]
Thank you for reporting this regression. It is fixed now via https://github.com/InfiniteAmmoInc/Yarn/commit/a4db7ee65368f3cf2d32cceebe8a84919d153e2b
