### ISSUE TITLE
Handling facial expressions

### ISSUE THREAD

**Issue by agustincordes** [InfiniteAmmoInc/Yarn#15]
It would be nice to have some way to trigger facial expressions in our characters. I was thinking that maybe tags were the answer but this is not feasible; tags are useful for editing the dialogue but I don't see how we could reuse them in our respective implementations as they're specific to each node (which contain several lines of dialogue).

Rather, a system could be devised in which we insert certain string codes in each line. I'm thinking something like this:

    Frank: [frown]Why not?

All that would be needed then is to pass this expression (if available) to Say() like this:

    public IEnumerator Say(string characterName, string text, string expression)

It's trivial then in Unity to trigger the respective blendshape or whatever is being used to animate character faces.

I guess the developer could implement this system separately, but I believe this is useful enough that it could be added to the main app.

**Comment by InfiniteAmmoInc** [comment]
So far we've left this up to each user's DialogueImplementation. i.e. in Night in the Woods for example, emoticons are parsed to setup expressions. :) :D :( etc...

**Comment by agustincordes** [comment]
Alright, thanks! Emoticons are a nicer approach. I'll stick to that. For non-standard ones, the syntax used for Emoji would be more consistent then:

    Frank: Why not? :frowning:

I'll close the issue!
