### ISSUE TITLE
Question about running Yarn as a web page vs an app

### ISSUE THREAD

**Issue by desplesda** [InfiniteAmmoInc/Yarn#20]
Currently, Yarn can be run as a web page, in the browser. This has its good points and bad points - running in a web view means you can link to it directly, and can run it in a browser tab if you like. Some people quite like that.

However, running in a web browser has its downsides: web pages can't access the filesystem, which means that 'saving' really means opening a new page containing the JSON. It also means that it can't use some especially fancy Node.js modules that could lead to some very nice features in the future.

If you run Yarn as an app, you get all the nice filesystem features, plus all of the feature possibilities that that unlocks, but it doesn't run in the browser.

There are some things that I'm poking at that would *require* running as an app, making running Yarn in the browser not possible.

So, I guess my questions (for both @InfiniteAmmoInc and anyone else who uses Yarn): How big of a deal would that be? Do people prefer to download the builds from the main page? Or do they download the source code and open the index.html?

**Comment by beeglebug** [comment]
I personally really like that it is available as a hosted web app. I think there is a lot more that we can do to make the functionality on par with a compiled app, especially if we set the bar higher on browser support (eg http://caniuse.com/#feat=filesystem), but if i'm the only person using it in the browser then i'm willing to get behind dropping support.

At the end of the day the best way to make a decision like that is with supporting data, and that can only really come from @InfiniteAmmoInc. Alex, do you have any analytics data on how often the web version is used, or by how many people?

**Comment by desplesda** [comment]
Yeah. The thing in particular that I'm thinking about is using something like Edge (https://github.com/tjanczuk/edge) to run the Yarn Spinner compiler (which is a .NET DLL) on your Yarn content. This would allow for things like syntax checking and lots else; however, Edge only works when you're not a web page, because it requires running a .NET runtime.

(I've looked into other options, like recompiling Yarn Spinner into Javascript using something like JSIL, but it feels rather messy and suboptimal.)

I guess the real question is: would having a smarter editor be worth the tradeoff for not being able to run in the webpage?

**Comment by InfiniteAmmoInc** [comment]
Although I don't have any hard data on how people are using Yarn, (closest I can think of trying is asking twitter lol) I think it's worth focusing on desktop app first in order to support more functionality. However, we could also try to maintain a web-only branch if that's still something of interest?

**Comment by desplesda** [comment]
It probably wouldn't be too hard to detect if Yarn is running in a browser page, and disable features.
