### ISSUE TITLE
Word wrap in editor?

### ISSUE THREAD

**Issue by tekknobabblr** [InfiniteAmmoInc/Yarn#24]
I'm trying to implement word wrap in the editor window. Been researching for hours now and no luck lol. It seems like it should already be working, based on what I've seen, since Yarn uses "TextArea".

Here's what we're seeing now:

![current](https://cloud.githubusercontent.com/assets/11084079/13377227/f508d8ce-dd9f-11e5-853f-528ba0e81461.jpg)

And a mock-up of what I'm thinking (how word wrap works in Notepad++, for example):

![should](https://cloud.githubusercontent.com/assets/11084079/13377262/5d900498-dda1-11e5-8399-e753ec239ed8.jpg)

Anyone have any ideas?

**Comment by desplesda** [comment]
Apologies if you’ve already looked, but have you checked out the documentation for ACE, the code editor that Yarn is using? 

https://github.com/ajaxorg/ace/

**Comment by tekknobabblr** [comment]
Ooh, no I have not! Thanks!

I got it! I added `editor.getSession().setUseWrapMode(true)` to knockout.ace on line 26, and that did exactly what I was looking for!

**Comment by desplesda** [comment]
Cool! You should open a pull request, so that @InfiniteAmmoInc can merge it into the main app!

**Comment by tekknobabblr** [comment]
Still a noob at GitHub, but I think I did it right lol.

Not sure if this is something that would go in the main branch yet or not, though. I mean, I wanted word wrap, but is that something everyone would want? Seems like something that will need a checkbox implemented to turn it on or off.

**Comment by charblar** [comment]
Resolved in PR https://github.com/InfiniteAmmoInc/Yarn/pull/25, closing.
