### ISSUE TITLE
replace current editor with ace editor

### ISSUE THREAD

**Issue by seiyria** [InfiniteAmmoInc/Yarn#4]
The current editor could be replaced with [Ace Editor](http://ace.c9.io). Questions are:

* What syntax is there? Preferably, a grammar would help but a bunch of examples can serve that purpose just as well.
* What colors should the syntax highlighter be?

**Comment by AlecHolowka** [comment]
Commands: << >>
Links: [[ ]]
Comments: //

The colours are in the style css under "conditionbounds," "linkbounds" and "comment" classes, I'll grab codes

**Comment by AlecHolowka** [comment]
.linkname
{
	color: #3ecfe9;
}

.linkbounds
{
	color: #0ec0e0;
}

.condition
{
	color: #e93ecf;
}

.conditionbounds
{
	color: #e00ec0;
}

.comment
{
	color: #44fe66;
}

**Comment by seiyria** [comment]
here's what I have:

![](http://puu.sh/gZa2v/884584e331.jpg)

PR incoming after I get rid of the top bar

**Comment by AlecHolowka** [comment]
Very cool :) does it scroll too?

The other small detail is sometimes the connections [[]] have pipes | like so [[This is a dialogue option|NodeName]]

In this case we were highlighting the [[ and ]] and the mode name and the pipe | but not the option text.

Not a big deal but it helps readability a bit.

Thanks so much. :) I wish we'd heard of Ace earlier.

**Comment by seiyria** [comment]
Yeah, it will scroll. Hm, you might not want to merge my PR yet then, the regex for it is simple: `[a-zA-Z0-9 ]+` so it doesn't account for things like vertical bars either.

I'll see if I can change the regex to make it more readable; I agree, it would be much easier to read if the text wasn't colored as well!

**Comment by InfiniteAmmoInc** [comment]
Not sure if this code helps at all, but this is what was being used before:

[code]
text = text.replace(/\</g, '&lt;');
		text = text.replace(/\>/g, '&gt;');
		text = text.replace(/\&lt;\&lt;(.*?)\&gt;\&gt;/g, '<p class="conditionbounds">&lt;&lt;</p><p class="condition">$1</p><p class="conditionbounds">&gt;&gt;</p>');
		text = text.replace(/\[\[([^\|]*?)\]\]/g, '<p class="linkbounds">[[</p><p class="linkname">$1</p><p class="linkbounds">]]</p>');
		text = text.replace(/\[\[([^\[\]]*?)\|([^\[\]]*?)\]\]/g, '<p class="linkbounds">[[</p>$1<p style="color:red"><p class="linkbounds">|</p><p class="linkname">$2</p><p class="linkbounds">]]</p>');
		text = text.replace(/\/\/(.*)?($|\n)/g, '<span class="comment">//$1</span>\n');
		text = text.replace(/\/\*((.|[\r\n])*)?\*\//gm, '<span class="comment">/*$1*/</span>');
		text = text.replace(/\/\%((.|[\r\n])*)?\%\//gm, '<span class="comment">/%$1%/</span>');
[/code]

**Comment by InfiniteAmmoInc** [comment]
Here's the old code for that, not sure if it'd be helpful or not :)

```
		text = text.replace(/\[\[([^\|]*?)\]\]/g, '<p class="linkbounds">[[</p><p class="linkname">$1</p><p class="linkbounds">]]</p>');
		text = text.replace(/\[\[([^\[\]]*?)\|([^\[\]]*?)\]\]/g, '<p class="linkbounds">[[</p>$1<p style="color:red"><p class="linkbounds">|</p><p class="linkname">$2</p><p class="linkbounds">]]</p>');
		text = text.replace(/\/\/(.*)?($|\n)/g, '<span class="comment">//$1</span>\n');
		text = text.replace(/\/\*((.|[\r\n])*)?\*\//gm, '<span class="comment">/*$1*/</span>');
		text = text.replace(/\/\%((.|[\r\n])*)?\%\//gm, '<span class="comment">/%$1%/</span>');
```

**Comment by seiyria** [comment]
Just showing that each component can be colored separately:

![](http://puu.sh/gZlCi/8572cd0281.png)

I'll adjust these colors to match what they previously were and show you how to tweak them after I update my PR.

**Comment by InfiniteAmmoInc** [comment]
Awesome. :D

**Comment by seiyria** [comment]
Alright, here is the CSS you'd have to change: https://github.com/seiyria/Yarn/blob/master/app/js/libs/theme-yarn.js#L14-L38

Here are what the specific tokens are:
https://github.com/seiyria/Yarn/blob/master/app/js/libs/mode-yarn.js#L14-L51

If a token is, say, `paren.lcomm` that will get expanded into the CSS classes `.ace-paren.ace-lcomm` so you can target it that way. 

Conversion is as follows:

```
comment => comment
*comm => condition (command?) -- this is the << >> ones
*link => link -- this is the [[ ]] ones
```

Feel free to pull it down and try it out and let me know if anything is broken.
