### ISSUE TITLE
Documentation for file formats

### ISSUE THREAD

**Issue by edkek** [InfiniteAmmoInc/Yarn#45]
I can't seem to find any documentation for the different file formats that Yarn exports.  I want to write a library for [LibGDX](https://github.com/libgdx/libgdx) that adds support for the files Yarn exports.

I can get a general idea in [data.js](https://github.com/InfiniteAmmoInc/Yarn/blob/master/app/js/classes/data.js#L285) but I think it'd be useful to have written documentation somewhere for future developers who want to use Yarn for other languages/frameworks other than Unity. (maybe the wiki?)

I can document them as I go, but I don't know where to put it..

**Comment by desplesda** [comment]
Best way to do it would be adding a wiki page, I think!

**Comment by charblar** [comment]
Initialized the wiki for repository, I believe now that the home page is created others can contribute. Closing.
