### ISSUE TITLE
[Question] Is there a way to navigate to a node without a user choice button?

### ISSUE THREAD

**Issue by Barryrowe** [InfiniteAmmoInc/Yarn#46]
I'm looking for a way to do the following:

```
<<if visited("SectionA") is false>>
Hi There
*Instead of a line of text, the "next" button takes you to | SectionA.Details*
<<else>>
Remember me?
[[What was your story again? | SectionA.Details]]
[[Yeah, gotta go though! | SectionA.Exit]]
<<endif>>
```

I can't find any documentation that shows how to make this happen. The best I can find is to present a button on the first pass through as the only user option. It would feel much more fluid if there was only the basic next button on the first visit. Is this possible?

**Comment by desplesda** [comment]
Do this:

````
<<if visited("SectionA") is false>>
Hi There
[[SectionA.Details]]
<<else>>
````

When you link to a node but don't provide a caption, Yarn Spinner interprets it as a command to jump directly to that node.

**Comment by Barryrowe** [comment]
Perfect! thanks. I figured there would be a way to do this that I just overlooked.
