### ISSUE TITLE
Command to go automatically from a node to another without options

### ISSUE THREAD

**Issue by bottazzi1900** [InfiniteAmmoInc/Yarn#56]
Hello. I would ask if there is a way to connect two nodes without insert an option that the player must click.
For example, I have:

NODE1
[[Talk with him | NODE2]]
[[HIt him | NODE3]]

NODE2
Hello

I want that from the NODE2, the player returns automatically to the NODE1. Do you know if there's a specific command?

**Comment by charblar** [comment]
[[Return|NODE1]] should work. Depending on what you're parsing with it may or may not display the option if there is only one option and instead just jump to the connected node.
