### ISSUE TITLE
Scrolling/Panning the file doesn't work on Windows Build

### ISSUE THREAD

**Issue by InfiniteAmmoInc** [InfiniteAmmoInc/Yarn#6]
Clicking and dragging on the back of the node area doesn't let you drag the screen around anymore. Seems to only happen with the Windows build.

Scrolling to zoom doesn't seem to work either.

Clicking the area around the node editor window to close it also doesn't work.

**Comment by 3noneTwo** [comment]
I've briefly checked out Yarn on Windows (Win 7, 64-bit) by downloading the source, locating the 'index.html' file inside the 'app' folder, and opening it in NWJS. Panning seems to be working (both by left-click-dragging and middle-click-dragging on the background), and I can close the node editor window by clicking outside it.

Zooming with the scroll-wheel works, but it seems to zoom in single-percent increments. (Better than the previous update though, which was zooming in increments of *fractions* of a pixel.)

**Comment by InfiniteAmmoInc** [comment]
This should be fixed now, updated the zoom speed to be different on Mac/Windows. :)

**Comment by 3noneTwo** [comment]
It seems this was broken at some point, for the Windows build at least? Clicking and dragging with any mouse button results in a selection box.

Middle-click-drag would be perfect for panning. Keep the selection box for left-click-drag though, that mouse action makes sense. (Maybe remove the selection box for right-click-drag too, it's a bit goofy.)

**Comment by InfiniteAmmoInc** [comment]
Hi! Right now "alt-drag" works for panning. Middle-click-drag seems like a good addition tho!
