### ISSUE TITLE
exactly 262 errors while installing Yarn in my project's forlder.

### ISSUE THREAD

**Issue by Dreaddisk** [InfiniteAmmoInc/Yarn#60]
After put the yarn folder in my projects folder. I get in my console 262 errors from the app JS file.

**Comment by bowlercaptain** [comment]
Hey Dreaddisk - it sounds like you've put Yarn inside of a Unity project; Yarn is actually meant to be used outside of Unity, like a text editor or any other application. It has "js" files, but as you've seen, they're not built on unity's API, they compose a NW.JS app.

You should use Yarn outside of your project, but when you go to save and export your scripts, *those* you would want to save to your project's assets folder. If you're interested in a Unity-specific loader for yarn files, check out the YarnSpinner project (https://github.com/thesecretlab/YarnSpinner).

You didn't mention Unity in your issue but I *assume* that's what you meant given you mentioned the console. If something else is going on, feel free to let me know.

**Comment by Dreaddisk** [comment]
Hello Robert. I have a really stupid question to make, How can I open the YarnSpinner editor? and now that we are at it, how can I also open the Yarn editor? Thank you, and sorry, but I'm really confuse because I can't find any exe file that tells me how can I open the editor.

________________________________

**Comment by charblar** [comment]
The Yarn editor can be opened via Yarn/app/index.html, for information on YarnSpinner please see the respective repo [here](https://github.com/thesecretlab/YarnSpinner).
