### ISSUE TITLE
Panning using Alt+Drag produces heavy lag immediately

### ISSUE THREAD

**Issue by tlein** [InfiniteAmmoInc/Yarn#62]
**Problem:** When using Alt+Drag to pan the canvas it will work smoothly for ~1 second and then suffer from heavy slowdown. Provided is a screenshot with an example. 
![yarn_lag](https://user-images.githubusercontent.com/815242/36436389-b4d376f0-1629-11e8-9c0f-a3919070c4a6.gif)
This problem occurs in both master (commit c353da7604b3cb9e3bd14897a3dc64601eebf9e5 at the time of writing this issue), and in the released 2016-08-15 build. I have only confirmed it in Windows.

I opened the devtools and profiled the action, nothing immediately jumps out, there's some garbage collection spikes but only 2 of them within a 5 second timeframe. Everything else seemed consistent across the entire profiling session.

**Comment by benswinden** [comment]
Found the commit that broke it.. it's been busted for a long time haha.. wondering why nobody else brought this up?
Here's the offending commit:
https://github.com/InfiniteAmmoInc/Yarn/commit/cd6f73a628f8f9c6ec12dd9b59aac7b5773cd3f8

**Comment by AndrewD2** [comment]
Probably easiest for you to fork and submit and PR.

**Comment by charblar** [comment]
Added to master in https://github.com/InfiniteAmmoInc/Yarn/commit/7e2238547f2841a20fa1b1d4329ca4672b1eb644, closing.
