### ISSUE TITLE
Brackets cause issues with inputted text

### ISSUE THREAD

**Issue by SkyAphid** [InfiniteAmmoInc/Yarn#69]
Sorry for the weird title. To avoid confusion, I've attached a screenshot to hopefully explain the problem better.

My game uses a tag system of its own for identifying characters and objects, such as [[PLAYER_NAME]]. Coincidentally, you guys use the same scheme for indicating branching dialogue. This has caused a small issue, as you can see in the screenshot.

A simple solution is to just have it identify the last set of brackets for indicating branching dialogue, rather than having it select the first. 

Thank you for your time! And the software works, looks, and feels great!

![yarn bug](https://user-images.githubusercontent.com/6147299/41747013-19fe15ba-7572-11e8-9e96-a4906b1fd95b.PNG)

**Comment by blurymind** [comment]
I think your syntax is incorrect.
The brackets are used for branching dialogue choices, not for calling variables like that.
Your card is not even branching

I would assume that it should be 
`$PLAYER_NAME`
@jhayley can you advise? :)

**Comment by SkyAphid** [comment]
We use a custom game engine, it's not part of any existing toolset. We were going to add support for Yarn to it, but ran into this bug. It's a pretty simple fix, you just need to switch the ending bracket identifier to use the last set rather than the first.

**Comment by SkyAphid** [comment]
I took a look at the code, if I'm not mistaken, the problem is in app.js, getHighlightedText(). You're using text.replace(), you should try text.substring() with text.lastIndexOf(). (Assuming JS has an equivalent of that, I use Java primarily). I'll see if I can fix it myself.

**Comment by SkyAphid** [comment]
I've fixed it. You guys can copy it over into your repo if you want. Though since I'm not familiar with the project code, these may not be the best solutions.

The edited files, `app.js, line 772,` and `mode-yarn.js, line 43,` can be found here:

mode-yarn changes, line 43:
https://pastebin.com/iRzzpZ4G
I've set up the bracket regex to always use the last occurrence of the brackets

app.js changes, line 772:
https://pastebin.com/GCTM3vAE
I've removed the regex usage and replaced it with more traditional code that's easier to read, using indexOf() and lastIndexOf() to detect the brackets correctly.

**Comment by blurymind** [comment]
@SkyAphid is the problem you describe a cosmetic issue with the editor? The letter coloring?

Yarn is just the editor, yarnspinner is the runtime to interpret the data. There is also bondage.js.
What game engine are you using? :)

**Comment by SkyAphid** [comment]
It's definitely cosmetic and appears to work fine on export, but it's still hard to work with. I tried editing your code but had a bit of trouble wiring everything up the way I wanted, so I ultimately ended up [writing my own dialogue editor.](https://github.com/SkyAphid/JDialogue) Thanks anyway for your time! I really appreciate it.

**Comment by charblar** [comment]
Issue has been dropped, closing.
