### ISSUE TITLE
No connections are drawn when opening a Yarn file

### ISSUE THREAD

**Issue by swakdaddy** [InfiniteAmmoInc/Yarn#78]
![image](https://user-images.githubusercontent.com/197153/44591986-05ca7780-a774-11e8-8de6-785a7274ed83.png)

OS: Windows 10.

Repro steps:
- Open Yarn version 0.2.1 for Windows.
- File -> Open -> Sally.yarn.txt
- Observe Yarn load the nodes, but draw no connections between nodes.

Including a file I know isn't working.

Thanks!

[Sally.yarn.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2318870/Sally.yarn.txt)

**Comment by julsam** [comment]
Thank you for your reporting this bug :+1: 

It seems like the issue comes from the line ending. When using the yarn.txt save format, Yarn is expecting only Unix type line ending and doesn't interpret correctly CR that Windows add. By default Yarn saves using LF only, but I guess the text editor you used changed it to CRLF.

Should be easy to fix, but in the meantime you can convert your files from the Windows format to the Unix one and the connections should be back :wink: 
Here's your file converted: [Sally.yarn.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2320610/Sally.yarn.txt)

Another quickfix would be to save it as a json file.

**Comment by swakdaddy** [comment]
Thanks for the great info and the source of the problem.
I'm not sure what editor added CR. I only used Notepad++ and Visual Studio 2017. 
I just tested editing/saving with whitespace visible and neither added CR.
I'll be sure to keep an eye out in the future.

Thank you! :-)

**Comment by blurymind** [comment]
This works fine in the electron version. Just tested it now.

Download it from
https://github.com/InfiniteAmmoInc/Yarn/pull/80

**Comment by blurymind** [comment]
Can you try if it works in the electron version 
https://github.com/InfiniteAmmoInc/Yarn/pull/80

I wonder how to fix this

**Comment by blurymind** [comment]
ok I discovered something:
- the problematic file gets detected as a twee file,
- the fixed file from @julsam is detected as yarn text

**Comment by desplesda** [comment]
Fixed in c50b77c.

**Comment by swakdaddy** [comment]
So I noticed that this fix doesn't seem to be included in Yarn-master somehow when you download the ZIP from Git.  I opened up data.js and added the fix manually, but it doesn't seem to work.
Dumb question, but do I need to compile something to get it to work?

**Comment by blurymind** [comment]
Please attach the example file :)

**Comment by swakdaddy** [comment]
The example file is already attached in the original post. See Sally.yarn.txt above.
It has the Windows-style line endings.
But, the problem is that this fix isn't in the git repo it seems.  At least, not when I download it like this:

![image](https://user-images.githubusercontent.com/197153/56093150-d8614400-5e92-11e9-9e2a-a7e6ed8041e1.png)

**Comment by blurymind** [comment]
@swakdaddy this was fixed on the electron branch. You need to use that instead of master 
https://github.com/blurymind/Yarn/releases/tag/0.3.6

**Comment by swakdaddy** [comment]
@blurymind - Ah thanks. I'll grab the electron branch then since it seems you guys have been working more on it!

**Comment by blurymind** [comment]
It has alot of the issues here fixed, it's just not the default branch yet
for some reason
