### ISSUE TITLE
Does opening twee files still work?

### ISSUE THREAD

**Issue by fragmental** [InfiniteAmmoInc/Yarn#83]
Every twee file I have tried to open with the Yarn editor has caused the error "Unknown filetype!".  This includes twee files that were exported from the Yarn editor.

However, I was able to open the twee file if it ended in .txt, and while the nodes were all there they had lost all their connections and the syntax for the connections was the same as it had been in twine, which doesn't work in yarn.

Bonus question: What file types can be opened?

**Comment by fragmental** [comment]
I was using the release version of the yarn editor (2016-08-15) and I tried the latest code.  Still has the same problem with .twee files, but I tried exporting a tw2 file and importing it and it seemed to work fine except that the connections were lost.  It was weird too, because the syntax was mostly fine, except that one line was missing it's carriage return/new line, and there were some additional spaces at the end of two of the titles(One title had one space, and another title had two spaces). When I fixed those two issues most of the connections return.  The remaining connections return when I do something arbitrary like opening and closing the affected node a second time.

The scene is a simple scene with 3 nodes and 4 connections.

**Comment by julsam** [comment]
Not sure if it's related to #78 & #79 or not 🤔 
Can you post your files here (both .twee and .tw2) so i can try to reproduce it?

**Comment by fragmental** [comment]
[TestStory1.zip](https://github.com/InfiniteAmmoInc/Yarn/files/2403697/TestStory1.zip)

Here's a zip file that contains the yarn story in .yarn.txt and a .twee and a .tw2 created with "save as twee" and "save as tw2" in the yarn editor.

I have also tried creating a twee with twine 1.4.2 and it also has the same result in yarn ("Unknown filetype!").

I have tested the twee from yarn editor in twine 1.4.2 and it works fine there.  I have not tested the tw2, from yarn, in other software.

**Comment by fragmental** [comment]
I tested the twee file created with yarn, in tweego and it fails because it's looking for `:: StoryTitle`.
Adding:
```
:: StoryTitle
(Your Story Title)
```
to the twee makes it work, though.

**Comment by fragmental** [comment]
Discovered something interesting.  Renaming a .twee to .tw2 before import seems to work fine, in yarn.

**Comment by fragmental** [comment]
And I have also confirmed that if I edit the tw2 file, and remove the spaces between the Node name and the position, it then works correctly when I open it with the Yarn editor.

**Comment by fragmental** [comment]
I have also installed twee2 and tested the tw2 file with it and it works fine, with or without the extra spaces.

**Comment by blurymind** [comment]
thank you for submitting this report.
I have fixed both bugs in my pull here
https://github.com/InfiniteAmmoInc/Yarn/pull/80
