### ISSUE TITLE
Lag in large yarn file when repositioning cursor

### ISSUE THREAD

**Issue by Flyingvette** [InfiniteAmmoInc/Yarn#85]
Using yarn in windows 10. Roughly 20k words and 50 nodes. Scrolling and moving around works well / smoothly, as does creating connections. However, double clicking on a node to open it has a noticeable lag, and repositioning the cursor via mouse click in a node has noticeable lag. Writing is completely smooth. Has anyone else experienced this?

**Comment by blurymind** [comment]
Can you share a file that would cause this- for testing :)

**Comment by Flyingvette** [comment]
Here you go, thank you for looking at it :) I confirmed that moving the cursor via the arrow keys is smooth and lag free - its any time the mouse is used to click that the lag shows up.
[lag test 1 -  11-28-18.json.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2627573/lag.test.1.-.11-28-18.json.txt)

**Comment by Flyingvette** [comment]
Opened this file on a modern laptop and the problem went away. It seems that either the overhead on this size file is just too much for an older processor or maybe there is an unaddressed issue in the install or one of the associated files.

**Comment by blurymind** [comment]
It's still useful to have a file to stress test yarn with :) Thank you for providing one. I will close this issue for now.
Will reopen it if the bug comes back
