### ISSUE TITLE
Version 0.2.1 Yarn Files Break in Version 0.3.5 of Yarn Portable

### ISSUE THREAD

**Issue by tomdominer** [InfiniteAmmoInc/Yarn#91]
I've created a simple story introduction file in yarn which doesn't get properly parsed in Yarn 0.3.5.

Nodes appear to be missing (i.e. Story.Apartment.Forms doesn't appear) and connections are lost. Also, if you open any node with connections (i.e. Choice.Green.Circle) it seems to break the 0.3.5 editor as you cannot close the node afterwards.

**File Open in 0.2.1**
![yarn_file_open_in_0_2_1](https://user-images.githubusercontent.com/8956351/52207744-4aefeb00-2876-11e9-86b7-85f560a86247.jpg)

**File Open in 0.3.5**
![yarn_file_open_in_0_3_5](https://user-images.githubusercontent.com/8956351/52207749-4deadb80-2876-11e9-88c7-02a1b7dd291b.jpg)

**Yarn File Causing The Problems**
[Act1.Story.yarn.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2827848/Act1.Story.yarn.txt)

**Comment by tomdominer** [comment]
Delving a bit deeper, it seems to be related to the newer version of yarn not being able to handle node connections without a label. Using the YarnSpinner documentation as an example, if you just put in [[GoToCity]] into a story node, without that node existing, the editor tries to create a node connection seems to fail, making about five new nodes and stops you from closing the node editor window.

**Comment by blurymind** [comment]
Thank you for attaching an example. Some of the new features have
introduced a few regressions. I have fixed some of them on git, but haven't
released a build yet

**Comment by blurymind** [comment]
Hi, I can confirm that this has been fixed in the latest git version already via https://github.com/InfiniteAmmoInc/Yarn/commit/88e44eccb07434b10503d1499f57da2db1850de2 . I will soon release a new build. If you build electron version from git, it works

**Comment by blurymind** [comment]
build with a fix:
https://github.com/blurymind/Yarn/releases/tag/0.3.6

**Comment by tomdominer** [comment]
Check and fixed in version 0.3.6.
