### ISSUE TITLE
Yarn 0.3.5 Cannot Handle Node Connections Without a Label

### ISSUE THREAD

**Issue by tomdominer** [InfiniteAmmoInc/Yarn#92]
Using the Yarn Spinner `[example dialogue documentation](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/YarnSpinner-Dialogue/General-Usage.md)` as an example, if you create a new node and then paste in [[GoToCity]] as a node link without a lable, the editor seems to bug out. You cannot close the node, the text appears incorrectly and when you delete the text and then close the node the yarn editor has created 7 new node connections.

**Comment by blurymind** [comment]
Thank you for reporting. I will look into it

**Comment by blurymind** [comment]
can you provide an example file again please. It is really helpful with fixing these regressions

**Comment by blurymind** [comment]
I think this is the same as https://github.com/InfiniteAmmoInc/Yarn/issues/91, if so it has already been fixed.
I just need to release a bugfix build soon

**Comment by tomdominer** [comment]
Where should I be looking for a new build @blurymind ? On the [main fork page](https://github.com/blurymind/Yarn)

**Comment by blurymind** [comment]
build with a fix:
https://github.com/blurymind/Yarn/releases/tag/0.3.6

**Comment by tomdominer** [comment]
Check and fixed in version 0.3.6.
