### ISSUE TITLE
Yarn 0.3.5 Automatically Creates New Nodes When Connecting To Same Node

### ISSUE THREAD

**Issue by tomdominer** [InfiniteAmmoInc/Yarn#93]
This one might not be a bug, I am not sure.

If you create a node with a choice, and one of those choices is to run the same node again, the editor creates a new node with the same name. I've included an example file. If you open it in the 0.3.5 editor and then open and close the "Choice 1" node, the editor creates a new "Choice 1" node window, even though one already exists.

[Choice.Test.yarn.txt](https://github.com/InfiniteAmmoInc/Yarn/files/2828075/Choice.Test.yarn.txt)

**Comment by blurymind** [comment]
this does indeed sound like a bug. thank you for reporting. I will look into it

**Comment by blurymind** [comment]
fixed this, will push a merge tonight :) Thank you for reporting and for providing an example file

**Comment by blurymind** [comment]
build with a fix:
https://github.com/blurymind/Yarn/releases/tag/0.3.6

**Comment by tomdominer** [comment]
Check and fixed in version 0.3.6.
